language: java
jdk:
 - oraclejdk8
# no ant defaults to maven
#script: ant main
#script:
#  - ./mvnw clean install
#  - bash <(curl -s https://codecov.io/bash)

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
